###########################################################
# Automation: [System] Clear TTS
###########################################################

- alias: "[System] Clear TTS Cache"
  trigger:
    - platform: time
      hours: "/24"
  condition:
    - condition: time
      weekday:
        - mon
  action:
    - service: tts.clear_cache
