###########################################################
# Automation: [System] Low Disk Space
###########################################################

- alias: "[System] SD Card Space at 90%"
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_
      above: 89
  action:
    - service: persistent_notification.create
      data:
        title: Low SD Card Space
        message: "SD card usage is at {{ states.sensor.disk_use_percent_.state }}%"
        notification_id: low_disk_space
    - service: notify.join_user1
      data_template:
        title: Low SD Card Space
        message: "SD card usage is at {{ states.sensor.disk_use_percent_.state }}%"
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/micro-sd.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
