###########################################################
# Automation: [System] Set Theme at Startup
###########################################################

- alias: "[System] Set Theme at Startup"
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: PmxMononight
