###########################################################
# Automation [System]: Z-Wave
###########################################################

# - alias: "[System] Z-Wave Soft Reset"
#   trigger:
#     platform: time
#     at: "2:30:00"
#   action:
#     service: zwave.soft_reset

- alias: "[System] Z-Wave Heal"
  trigger:
    - platform: time
      at: "02:30:00"
  action:
    - service: zwave.heal_network
