homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: !secret homeassistant_time_zone
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob: !include_dir_merge_named customize

http: !include configuration/http.yaml

# discovery:

hassio:
frontend: !include configuration/frontend.yaml
config:
updater:

# conversation:

ecobee:
  api_key: !secret ecobee_api_key
climate:
  platform: ecobee

sun:

cloud: !include configuration/cloud.yaml
cover: !include configuration/cover.yaml
# google_assistant: !include configuration/google_assistant.yaml
history:
influxdb: !include configuration/influxdb.yaml
logbook: !include configuration/logbook.yaml
logger: !include configuration/logger.yaml
notify: !include configuration/notify.yaml
recorder: !include configuration/recorder.yaml
tts: !include configuration/tts.yaml
zwave: !include configuration/zwave.yaml

group: !include_dir_merge_named group
# input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
script: !include_dir_merge_named script
# shell_command: !include_dir_merge_named shell_command

automation: !include automations.yaml
automation old: !include_dir_merge_list automation
# binary_sensor: !include_dir_merge_list binary_sensor
camera: !include_dir_merge_list camera
device_tracker: !include_dir_merge_list device_tracker
media_player: !include_dir_merge_list media_player
panel_custom: !include_dir_merge_list panel_custom
# scene: !include_dir_merge_list scene
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch

# ifttt:
#   key: !secret ifttt_key
