---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one to guarentee the order of
# the tabs of the view in the UI.
#
title: Mechanix
resources:
  # https://github.com/kuuji/button-card
  # https://community.home-assistant.io/t/lovelace-button-card/65981
  - url: /customcards/lovelace/button-card.js
    type: module

  # https://github.com/iammexx/home-assistant-config/tree/master/ui/darksky
  # https://community.home-assistant.io/t/custom-dark-sky-animated-weather-card/59816/272
  - url: /local/lovelace/dark-sky-weather-card.js?v=7.1
    type: module

  # https://github.com/kalkih/mini-media-player
  # https://community.home-assistant.io/t/lovelace-mini-media-player/68459
  - url: /customcards/lovelace/mini-media-player-bundle.js
    type: module

  # https://github.com/ciotlosm/custom-lovelace
  - url: /customcards/lovelace/custom-lovelace/entity-attributes-card/entity-attributes-card.js
    type: js
  - url: /customcards/lovelace/custom-lovelace/monster-card/monster-card.js
    type: js

  # https://github.com/nervetattoo/simple-thermostat
  # https://community.home-assistant.io/t/lovelace-simple-thermostat-card/82659
  - url: /customcards/lovelace/simple-thermostat.js
    type: module

  # https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /customcards/lovelace/slider-entity-row.js
    type: js

  # https://github.com/custom-cards/tracker-card
  - url: /customcards/lovelace/tracker-card.js?track=true
    type: module

  # https://github.com/custom-cards/vertical-stack-in-card
  - url: /customcards/lovelace/vertical-stack-in-card.js
    type: js

views:
  - !include lovelace/home.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/media.yaml
  - !include lovelace/computers.yaml
  - !include lovelace/security.yaml
  - !include lovelace/entry_codes.yaml
  - !include lovelace/irrigation.yaml
  - !include lovelace/devices.yaml
  - !include lovelace/system.yaml
