###########################################################
# Automation: [Notify] Door
###########################################################

- alias: "[Notify] Door Left Open and Leaving"
  trigger:
    - platform: state
      entity_id: group.people
      to: "not_home"
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.door_front
        state: "Open"
      - condition: state
        entity_id: sensor.door_back
        state: "Open"
      - condition: state
        entity_id: sensor.door_garage_entry
        state: "Open"
      - condition: state
        entity_id: sensor.door_garage_outside
        state: "Open"
  action:
    - service: notify.join_users
      data_template:
        title: "Door Left Open"
        message: "Don't Leave Yet! The {{ trigger.to_state.attributes.friendly_name }} was left open!"
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/door-open.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

- alias: "[Notify] Door Opened and Away"
  trigger:
    - platform: state
      entity_id:
        - sensor.door_front
        - sensor.door_back
        - sensor.door_garage_entry
        - sensor.door_garage_outside
      to: "Open"
  condition:
    - condition: state
      entity_id: group.people
      state: "not_home"
  action:
    - service: notify.join_users
      data_template:
        title: Door Opened
        message: "The {{ trigger.to_state.attributes.friendly_name }} opened and no one is home."
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/door-open.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

- alias: "[Notify] Door Left Open"
  trigger:
    - platform: state
      entity_id:
        - sensor.door_front
        - sensor.door_back
        - sensor.door_garage_entry
        - sensor.door_garage_outside
      to: "Open"
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: group.people
      state: "home"
    # - condition: template
    #   value_template: "{{(as_timestamp(now()) - as_timestamp(trigger.to_state.last_updated) | int > 600 )}}"
  action:
    - service: notify.join_users
      data_template:
        title: Door Open
        message: "The {{ trigger.to_state.attributes.friendly_name }} has been open for 5 minutes"
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/door-open.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
