###########################################################
# Automation: [Notify] Garage Door
###########################################################

- alias: "[Notify] Garage Door Open and Leaving"
  trigger:
    - platform: state
      entity_id: group.people
      to: "not_home"
  condition:
    - condition: state
      entity_id: cover.garage_door
      state: "open"
  action:
    - service: notify.join_users
      data_template:
        title: Garage Door Open
        message: "Don't Leave Yet! The garage door was left open!"
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/garage-open.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

- alias: "[Notify] Garage Door Open Away"
  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: "open"
  condition:
    - condition: state
      entity_id: group.people
      state: "not_home"
  action:
    - service: notify.join_users
      data_template:
        title: Garage Door Open
        message: "The garage door opened and no one is home."
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/garage-open.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

- alias: "[Notify] Garage Door Left Open"
  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: "open"
      for:
        minutes: 45
  condition:
    - condition: state
      entity_id: group.people
      state: "home"
    # - condition: state
    #   entity_id: binary_sensor.garage_occupancy_on
    #   state: "off"
  action:
    - service: notify.join_users
      data_template:
        title: Garage Door Open
        message: "The garage door has been open for 45 minutes"
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/garage-open.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
