###########################################################
# Sensor: Devices
###########################################################

- platform: template
  sensors:
    device_athos:
      friendly_name: Athos
      value_template: "{{ 'Online' if is_state('device_tracker.athos', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:desktop-tower' if is_state('device_tracker.athos', 'home') else 'mdi:blur-off' }}"

    device_erebus:
      friendly_name: Erebus
      value_template: "{{ 'Online' if is_state('device_tracker.erebus', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:desktop-tower' if is_state('device_tracker.erebus', 'home') else 'mdi:blur-off' }}"

    device_mechanixcast:
      friendly_name: MechanixCast
      value_template: "{{ 'Online' if is_state('device_tracker.mechanixcast', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:cast' if is_state('device_tracker.mechanixcast', 'home') else 'mdi:cast-off' }}"

    device_echo_dot_family_room:
      friendly_name: Echo Dot Family Room
      value_template: "{{ 'Online' if is_state('device_tracker.echo_dot_family_room', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:server-network' if is_state('device_tracker.echo_dot_family_room', 'home') else 'mdi:blur-off' }}"

    device_echo_dot_living_room:
      friendly_name: Echo Dot Living Room
      value_template: "{{ 'Online' if is_state('device_tracker.echo_dot_living_room', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:server-network' if is_state('device_tracker.echo_dot_living_room', 'home') else 'mdi:blur-off' }}"

    device_ecobee:
      friendly_name: Ecobee
      value_template: "{{ 'Online' if is_state('device_tracker.ecobee', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:nest-thermostat' if is_state('device_tracker.ecobee', 'home') else 'mdi:blur-off' }}"

    device_epson_workforce_845:
      friendly_name: Epson Workforce 845
      value_template: "{{ 'Online' if is_state('device_tracker.epson_workforce_845', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:printer' if is_state('device_tracker.epson_workforce_845', 'home') else 'mdi:blur-off' }}"

    device_googlehome:
      friendly_name: Google Home
      value_template: "{{ 'Online' if is_state('device_tracker.googlehome', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:google-assistant' if is_state('device_tracker.googlehome', 'home') else 'mdi:blur-off' }}"

    device_harmony_bedroom:
      friendly_name: Harmony Bedroom
      value_template: "{{ 'Online' if is_state('device_tracker.harmony_bedroom', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:remote' if is_state('device_tracker.harmony_bedroom', 'home') else 'mdi:blur-off' }}"

    device_harmony_living_room:
      friendly_name: Harmony Living Room
      value_template: "{{ 'Online' if is_state('device_tracker.harmony_living_room', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:remote' if is_state('device_tracker.harmony_living_room', 'home') else 'mdi:blur-off' }}"

    device_kindle:
      friendly_name: Kindle
      value_template: "{{ 'Online' if is_state('device_tracker.kindle', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:tablet' if is_state('device_tracker.kindle', 'home') else 'mdi:blur-off' }}"

    device_kindle_hd8:
      friendly_name: Kindle Fire HD8
      value_template: "{{ 'Online' if is_state('device_tracker.kindle_hd8', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:tablet' if is_state('device_tracker.kindle_hd8', 'home') else 'mdi:blur-off' }}"

    device_kindle_hdx:
      friendly_name: Kindle Fire HDX
      value_template: "{{ 'Online' if is_state('device_tracker.kindle_hdx', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:tablet' if is_state('device_tracker.kindle_hdx', 'home') else 'mdi:blur-off' }}"

    device_leappad:
      friendly_name: LeapPad
      value_template: "{{ 'Online' if is_state('device_tracker.leappad', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:tablet' if is_state('device_tracker.leappad', 'home') else 'mdi:blur-off' }}"

    device_mtcd_mazda:
      friendly_name: MTCD [Mazda]
      value_template: "{{ 'Online' if is_state('device_tracker.mtcd_mazda', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:car-connected' if is_state('device_tracker.mtcd_mazda', 'home') else 'mdi:blur-off' }}"

    device_nasya:
      friendly_name: Nasya
      value_template: "{{ 'Online' if is_state('device_tracker.nasya', 'home') or is_state('device_tracker.nasya_wifi', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:laptop' if is_state('device_tracker.nasya', 'home') or is_state('device_tracker.nasya_wifi', 'home') else 'mdi:laptop-off' }}"

    device_opengarage:
      friendly_name: OpenGarage
      value_template: "{{ 'Online' if is_state('device_tracker.opengarage', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:garage' if is_state('device_tracker.opengarage', 'home') else 'mdi:blur-off' }}"

    device_shield_bedroom:
      friendly_name: Shield [Bedroom]
      value_template: "{{ 'Online' if is_state('device_tracker.shield_bedroom', 'home') or is_state('device_tracker.shield_wifi_bedroom', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:cast' if is_state('device_tracker.shield_bedroom', 'home') or is_state('device_tracker.shield_wifi_bedroom', 'home') else 'mdi:cast-off' }}"

    device_shield_living_room:
      friendly_name: Shield [Living Room]
      value_template: "{{ 'Online' if is_state('device_tracker.shield_living_room', 'home') or is_state('device_tracker.shield_wifi_living_room', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:cast' if is_state('device_tracker.shield_living_room', 'home') or is_state('device_tracker.shield_wifi_living_room', 'home') else 'mdi:cast-off' }}"

    device_rachio:
      friendly_name: Rachio
      value_template: "{{ 'Online' if is_state('device_tracker.rachio', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:water-pump' if is_state('device_tracker.rachio', 'home') else 'mdi:blur-off' }}"

    device_rasplex:
      friendly_name: RasPlex
      value_template: "{{ 'Online' if is_state('device_tracker.rasplex', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:plex' if is_state('device_tracker.rasplex', 'home') else 'mdi:blur-off' }}"

    device_macbook:
      friendly_name: MacBook
      value_template: "{{ 'Online' if is_state('device_tracker.macbook', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:laptop-mac' if is_state('device_tracker.macbook', 'home') else 'mdi:laptop-off' }}"

    device_samsung_galaxy_camera:
      friendly_name: Samsung Galaxy Camera
      value_template: "{{ 'Online' if is_state('device_tracker.samsung_galaxy_camera', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:camera' if is_state('device_tracker.samsung_galaxy_camera', 'home') else 'mdi:camera-off' }}"

    device_samsung_ml2525w:
      friendly_name: Samsung ML-2525w
      value_template: "{{ 'Online' if is_state('device_tracker.samsung_ml2525w', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:printer' if is_state('device_tracker.samsung_ml2525w', 'home') else 'mdi:blur-off' }}"

    device_smartwatch_3:
      friendly_name: Sony Smartwatch 3
      value_template: "{{ 'Online' if is_state('device_tracker.sony_smartwatch_3', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:watch' if is_state('device_tracker.sony_smartwatch_3', 'home') else 'mdi:blur-off' }}"

    device_sony_tv:
      friendly_name: Sony TV
      value_template: "{{ 'Online' if is_state('device_tracker.sony_tv', 'home') or is_state('device_tracker.sony_tv_wifi', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:television' if is_state('device_tracker.sony_tv', 'home') or is_state('device_tracker.sony_tv_wifi', 'home') else 'mdi:blur-off' }}"

    device_tcl_tv:
      friendly_name: TCL TV
      value_template: "{{ 'Online' if is_state('device_tracker.tcl_tv', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:television' if is_state('device_tracker.tcl_tv', 'home') else 'mdi:blur-off' }}"

    device_unifi:
      friendly_name: UniFi
      value_template: "{{ 'Online' if is_state('device_tracker.unifi_unraid', 'home') else 'Offline' }}"
      icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.unifi_unraid', 'home') else 'mdi:wifi-off' }}"
