###########################################################
# Sensor: Ecobee Thermostats
###########################################################

- platform: template
  sensors:
    house_thermostat_away_mode:
      value_template: >-
        {%- if is_state_attr('climate.home', 'away_mode', 'on') -%}
          Away
        {%- else -%}
          Home
        {%- endif %}
      icon_template: >
        {%- if is_state_attr('climate.home', 'away_mode', 'on') -%}
          mdi:walk
        {%- else %}
          mdi:home
        {%- endif %}

    occupancy_home:
      friendly_name: Home Occupancy
      value_template: >-
        {%- if is_state("binary_sensor.home_occupancy", "on") -%}
          Occupied
        {%- else -%}
          Clear
        {%- endif %}
      icon_template: >
        {%- if is_state("binary_sensor.home_occupancy", "on") -%}
          mdi:account
        {%- else -%}
          mdi:account-off
        {%- endif %}

    occupancy_ethan:
      friendly_name: "Ethan's Room Occupancy"
      value_template: >-
        {%- if is_state("binary_sensor.ethan_occupancy", "on") -%}
          Occupied
        {%- else -%}
          Clear
        {%- endif %}
      icon_template: >
        {%- if is_state("binary_sensor.ethan_occupancy", "on") -%}
          mdi:account
        {%- else -%}
          mdi:account-off
        {%- endif %}

    occupancy_kitchen:
      friendly_name: Kitchen Occupancy
      value_template: >-
        {%- if is_state("binary_sensor.kitchen_occupancy", "on") -%}
          Occupied
        {%- else -%}
          Clear
        {%- endif %}
      icon_template: >
        {%- if is_state("binary_sensor.kitchen_occupancy", "on") -%}
          mdi:account
        {%- else -%}
          mdi:account-off
        {%- endif %}

    occupancy_office:
      friendly_name: Office Occupancy
      value_template: >-
        {%- if is_state("binary_sensor.office_occupancy", "on") -%}
          Occupied
        {%- else -%}
          Clear
        {%- endif %}
      icon_template: >
        {%- if is_state("binary_sensor.office_occupancy", "on") -%}
          mdi:account
        {%- else -%}
          mdi:account-off
        {%- endif %}
