###########################################################
# Sensor: Locks
###########################################################

- platform: template
  sensors:
    lock_front_last_state:
      friendly_name: Front Door Status
      value_template: !secret lock_front_last_state_value
      icon_template: >
        {% if is_state('sensor.lock_front_alarm_type', '19') %}
          {% if is_state('sensor.lock_front_alarm_level', '1') %}
            mdi:dialpad
          {% elif is_state('sensor.lock_front_alarm_level', '2') %}
            mdi:dialpad
          {% else %}
            mdi:dialpad
          {% endif %}
        {% elif is_state('sensor.lock_front_alarm_type', '18') %}
          mdi:gesture-tap
        {% elif is_state('sensor.lock_front_alarm_type', '21') %}
          mdi:lock-reset
        {% elif is_state('sensor.lock_front_alarm_type', '22') %}
          mdi:lock-reset
        {% elif is_state('sensor.lock_front_alarm_type', '24') %}
          mdi:wifi
        {% elif is_state('sensor.lock_front_alarm_type', '25') %}
          mdi:wifi
        {% elif is_state('sensor.lock_front_alarm_type', '9') %}
          Lock Jammed
        {% elif is_state('sensor.lock_front_alarm_type', '161') %}
          mdi:alert
        {% else %}
          mdi:help-circle
        {% endif %}
