###########################################################
# Sensor: Remote
###########################################################

- platform: template
  sensors:
    remote_living_room:
      friendly_name: Living Room Activity
      icon_template: mdi:remote
      value_template: "{{ states.remote.living_room.attributes.current_activity }}"

    remote_bedroom:
      friendly_name: Bedroom Activity
      icon_template: mdi:remote
      value_template: "{{ states.remote.bedroom.attributes.current_activity }}"

    # remote_family_room:
    #   friendly_name: Family Room Activity
    #   icon_template: mdi:remote
    #   value_template: "{{ states.remote.family_room.attributes.current_activity }}"
