###########################################################
# Automation: Lights
###########################################################

- alias: "[Lights] Front on at Night"
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:20:00"
  condition:
    - condition: time
      before: "22:31:00"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.outside_front_light_switch

- alias: "[Lights] Front off at Night"
  trigger:
    - platform: time
      at: "22:32:00"
  action:
    - service: homeassistant.turn_off
      entity_id: switch.outside_front_light_switch

- alias: "[Lights] Turn on when Arrive"
  trigger:
    - platform: state
      entity_id: group.people
      from: "not_home"
      to: "home"
  condition:
    - condition: sun
      after: sunset
      after_offset: "-0:30:00"
    - condition: time
      before: "23:59:59"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.garage_entry_light_switch
    - service: light.turn_on
      entity_id: light.living_room_level
    - service: notify.join_users
      data_template:
        title: Welcome Home
        message: "The lights have been turned on."
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lightbulb-on.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
    - delay: "00:10:00"
    - service: homeassistant.turn_off
      entity_id: switch.garage_entry_light_switch

- alias: "[Lights] Turn off when Away"
  trigger:
    - platform: state
      entity_id: group.people
      from: "home"
      to: "not_home"
      for:
        minutes: 10
  condition:
    - condition: sun
      after: sunrise
      after_offset: "00:45:00"
    - condition: sun
      before: sunset
      before_offset: "-00:45:00"
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_light_switches
    - service: notify.join_users
      data_template:
        title: Lights Out
        message: "The lights have been turned off since no one is home."
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lightbulb.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
