###########################################################
# Automation: Locks
###########################################################

- alias: "[Lock] Front Door Lock at Night"
  trigger:
    - platform: time
      at: "22:00:00"
  condition:
    - condition: state
      entity_id: lock.lock_front_locked
      state: "unlocked"
  action:
    - service: lock.lock
      entity_id: lock.lock_front_locked

- alias: "[Lock] Front Door was Locked"
  trigger:
    - platform: state
      entity_id: lock.lock_front_locked
      to: "locked"
  action:
    - service: script.turn_off
      entity_id: script.lock_front_door_after_unlock

- alias: "[Lock] Front Door was Unlocked"
  trigger:
    - platform: state
      entity_id: lock.lock_front_locked
      to: "unlocked"
  condition:
    - condition: time
      after: "22:00:00"
      before: "09:00:00"
  action:
    - service: script.turn_on
      entity_id: script.lock_front_door_after_unlock

- alias: "[Lock] Front Door Lock when Away"
  trigger:
    - platform: state
      entity_id: group.people
      to: "not_home"
  condition:
    - condition: time
      after: "09:00:00"
      before: "22:00:00"
    - condition: state
      entity_id: lock.lock_front_locked
      state: "unlocked"
  action:
    - service: lock.lock
      entity_id: lock.lock_front_locked
    - service: notify.join_users
      data_template:
        title: Front Door Lock
        message: "The front door has been locked since no one is home."
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lock.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

- alias: "[Lock] Keypad Switch On"
  hide_entity: true
  trigger:
    - platform: state
      entity_id:
        - input_boolean.door_keypad_1_front_switch
        - input_boolean.door_keypad_2_front_switch
        - input_boolean.door_keypad_3_front_switch
        - input_boolean.door_keypad_4_front_switch
        - input_boolean.door_keypad_5_front_switch
        - input_boolean.door_keypad_6_front_switch
        - input_boolean.door_keypad_7_front_switch
        - input_boolean.door_keypad_8_front_switch
        - input_boolean.door_keypad_9_front_switch
        - input_boolean.door_keypad_10_front_switch
      to: "on"
  condition:
    - condition: template
      value_template: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = '_'.join(object_id.split('_')[2:-2]) %}
        {% set select_id = 'door_keypad_' ~ code_slot ~ '_access_schedule' %}
        {{ states['input_select'][select_id].state == 'Always' }}
  action:
    - service: lock.set_usercode
      data_template:
        node_id: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set lock_name = '_'.join(object_id.split('_')[3:-1]) %}
          {% set lock_id = 'lock_' ~ lock_name ~ '_locked' %}
          {{ states['lock'][lock_id].attributes.node_id }}
        code_slot: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = '_'.join(object_id.split('_')[2:-2]) %}
          {{ code_slot }}
        usercode: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = '_'.join(object_id.split('_')[2:-2]) %}
          {% set user_code_id = 'door_keypad_' ~ code_slot ~ '_code' %}
          {{ states['input_text'][user_code_id].state }}

- alias: "[Lock] Keypad Switch Off"
  hide_entity: true
  trigger:
    - platform: state
      to: "off"
      entity_id:
        - input_boolean.door_keypad_1_front_switch
        - input_boolean.door_keypad_2_front_switch
        - input_boolean.door_keypad_3_front_switch
        - input_boolean.door_keypad_4_front_switch
        - input_boolean.door_keypad_5_front_switch
        - input_boolean.door_keypad_6_front_switch
        - input_boolean.door_keypad_7_front_switch
        - input_boolean.door_keypad_8_front_switch
        - input_boolean.door_keypad_9_front_switch
        - input_boolean.door_keypad_10_front_switch
  condition:
    - condition: template
      value_template: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = '_'.join(object_id.split('_')[2:-2]) %}
        {% set select_id = 'door_keypad_' ~ code_slot ~ '_access_schedule' %}
        {{ states['input_select'][select_id].state == 'Always' }}
  action:
    - service: lock.set_usercode
      data_template:
        usercode: >-
          {{ range(1000, 9999) | random }}
        node_id: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set lock_name = '_'.join(object_id.split('_')[3:-1]) %}
          {% set lock_id = 'lock_' ~ lock_name ~ '_locked' %}
          {{ states['lock'][lock_id].attributes.node_id }}
        code_slot: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = '_'.join(object_id.split('_')[2:-2]) %}
          {{ code_slot }}

- alias: "[Lock] Keypad Temporary Code Start"
  hide_entity: true
  trigger:
    - platform: state
      to: "True"
      entity_id:
        - sensor.keypad_1_temp_lock_turn_on
        - sensor.keypad_2_temp_lock_turn_on
        - sensor.keypad_3_temp_lock_turn_on
        - sensor.keypad_4_temp_lock_turn_on
        - sensor.keypad_5_temp_lock_turn_on
        - sensor.keypad_6_temp_lock_turn_on
        - sensor.keypad_7_temp_lock_turn_on
        - sensor.keypad_8_temp_lock_turn_on
        - sensor.keypad_9_temp_lock_turn_on
        - sensor.keypad_10_temp_lock_turn_on
  condition:
    - condition: template
      value_template: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = object_id[7:-18] %}
        {% set input = 'door_keypad_' ~ code_slot ~ '_front_switch' %}
        {{ states['input_boolean'][input].state == 'on' }}
  action:
    - service: lock.set_usercode
      data_template:
        usercode: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-18] %}
          {% set input = 'door_keypad_' ~ code_slot ~ '_code' %}
          {{ states['input_text'][input].state }}
        node_id: >-
          {{ states['lock']['lock_front_locked'].attributes.node_id }}
        code_slot: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-18] %}
          {{ code_slot }}
    - service: notify.join_users
      data_template:
        title: "Temporary Code Enabled"
        message: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-18] %}
          {% set usercode_input = 'door_keypad_' ~ code_slot ~ '_code' %}
          {% set usercode = states['input_text'][usercode_input].state %}
          {% set name_input = 'door_keypad_' ~ code_slot ~ '_name' %}
          {% set name = states['input_text'][name_input].state %}
          {% set start_input = 'door_keypad_' ~ code_slot ~ '_date_start' %}
          {% set start = states['input_datetime'][start_input].state %}
          {% set end_input = 'door_keypad_' ~ code_slot ~ '_date_end' %}
          {% set end = states['input_datetime'][end_input].state %}
          The pin code {{ usercode }} is now temporarily enabled for {{ name }} from {{ start }} to {{ end }}.
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lock-smart.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

- alias: "[Lock] Keypad Temporary Code End"
  hide_entity: true
  trigger:
    - platform: state
      to: "True"
      entity_id:
        - sensor.keypad_1_temp_lock_turn_off
        - sensor.keypad_2_temp_lock_turn_off
        - sensor.keypad_3_temp_lock_turn_off
        - sensor.keypad_4_temp_lock_turn_off
        - sensor.keypad_5_temp_lock_turn_off
        - sensor.keypad_6_temp_lock_turn_off
        - sensor.keypad_7_temp_lock_turn_off
        - sensor.keypad_8_temp_lock_turn_off
        - sensor.keypad_9_temp_lock_turn_off
        - sensor.keypad_10_temp_lock_turn_off
  action:
    - service: lock.set_usercode
      data_template:
        usercode: >-
          {{ range(1000, 9999) | random }}
        node_id: >-
          {{ states['lock']['lock_front_locked'].attributes.node_id }}
        code_slot: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-19] %}
          {{ code_slot }}
    - service: notify.join_users
      data_template:
        title: "Temporary Code Disabled"
        message: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-19] %}
          {% set usercode_input = 'door_keypad_' ~ code_slot ~ '_code' %}
          {% set usercode = states['input_text'][usercode_input].state %}
          {% set name_input = 'door_keypad_' ~ code_slot ~ '_name' %}
          {% set name = states['input_text'][name_input].state %}
          The pin code {{ usercode }} for {{ name }} has now been removed.
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lock-smart.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
    - condition: template
      value_template: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = object_id[7:-19] %}
        {% set input = 'door_keypad_' ~ code_slot ~ '_access_schedule' %}
        {% set input_value = states['input_select'][input].state %}
        {{ input_value == 'Temporary' }}
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-19] %}
          {{ 'script.door_keypad_' ~ code_slot ~ '_delete' }}

- alias: "[Lock] Keypad One Time Use Code"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: lock.lock_front_locked
      to: "unlocked"
  condition:
    - condition: template
      value_template: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = object_id[7:-19] %}
        {% set input = 'door_keypad_' ~ code_slot ~ '_access_schedule' %}
        {% set input_value = states['input_select'][input].state %}
        {{ input_value == 'One Time' }}
  action:
    - service: lock.set_usercode
      data_template:
        usercode: >-
          {{ range(1000, 9999) | random }}
        node_id: >-
          {{ states['lock']['lock_front_locked'].attributes.node_id }}
        code_slot: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-19] %}
          {{ code_slot }}
    - service: notify.join_users
      data_template:
        title: "One Time Use Code Used"
        message: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-19] %}
          {% set usercode_input = 'door_keypad_' ~ code_slot ~ '_code' %}
          {% set usercode = states['input_text'][usercode_input].state %}
          {% set name_input = 'door_keypad_' ~ code_slot ~ '_name' %}
          {% set name = states['input_text'][name_input].state %}
          The pin code {{ usercode }} for {{ name }} has now been used and removed.
        data:
          icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lock-smart.png"
          smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
    - condition: template
      value_template: >-
        {% set object_id = trigger.to_state.object_id %}
        {% set code_slot = object_id[7:-19] %}
        {% set input = 'door_keypad_' ~ code_slot ~ '_access_schedule' %}
        {% set input_value = states['input_select'][input].state %}
        {{ input_value == 'One Time' }}
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set code_slot = object_id[7:-19] %}
          {{ 'script.door_keypad_' ~ code_slot ~ '_delete' }}
