###########################################################
# Automation: Office
###########################################################

- alias: Office Day Mode
  trigger:
  - platform: time
    at: 08:55:00
  condition:
  - condition: state
    entity_id: device_tracker.oneplus_6
    state: "home"
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.erebus_turn_on
  - service: light.turn_on
    data:
      entity_id: light.office_lamp
      brightness: 255
  - delay: '00:00:05'
  - service: light.turn_on
    data:
      entity_id: light.office_lamp
      color_temp: 181
  - service: light.turn_on
    data:
      entity_id: light.office_light
      brightness: 255
  - delay: '00:00:05'
  - service: light.turn_on
    data:
      entity_id: light.office_light
      color_temp: 181

- alias: Office Night Mode
  trigger:
  - platform: time
    at: '20:30:00'
  condition:
  - condition: state
    entity_id: light.office_light
    state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.office_lamp
      brightness: 204
      color_temp: 370
  - service: light.turn_on
    data:
      entity_id: light.office_light
      brightness: 140
      color_temp: 370
