###########################################################
# Automation: Pi-hole
###########################################################

- alias: "[Pi-hole] Disable"
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.pihole_time
  action:
    service: shell_command.pihole_disable

- alias: "[Pi-hole] Reset Disable Time"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: script.enable_pihole
    - platform: state
      entity_id: sensor.pihole_status
      from: "disabled"
      to: "enabled"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.pihole_time
      option: Select Time
