###########################################################
# Automation: Remote
###########################################################

- alias: "Harmony Bedroom Activity Changed"
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_bedroom
    from: Select Activity
  action:
    - service: script.turn_on
      entity_id: script.remote_bedroom

- alias: "Harmony Bedroom Power Off"
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_bedroom
    to: Power Off
  action:
    - service: remote.turn_off
      entity_id: remote.bedroom
    - service: input_select.select_option
      entity_id: input_select.remote_bedroom
      data_template:
        option: Select Activity

- alias: "Harmony Family Room Activity Changed"
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_family_room
    from: Select Activity
  action:
    - service: script.turn_on
      entity_id: script.remote_family_room

- alias: "Harmony Family Room Power Off"
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_family_room
    to: Power Off
  action:
    - service: remote.turn_off
      entity_id: remote.family_room
    - service: input_select.select_option
      entity_id: input_select.remote_family_room
      data_template:
        option: Select Activity

- alias: "Harmony Living Room Activity Changed"
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_living_room
    from: Select Activity
  action:
    - service: script.turn_on
      entity_id: script.remote_living_room

- alias: "Harmony Living Room Power Off"
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_living_room
    to: Power Off
  action:
    - service: remote.turn_off
      entity_id: remote.living_room
    - service: input_select.select_option
      entity_id: input_select.remote_living_room
      data_template:
        option: Select Activity
