###########################################################
# Automation: Remote
###########################################################

- alias: Harmony Living Room Activity
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_living_room
    from: Select Activity
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data_template:
        activity: >
          {% if is_state("input_select.remote_living_room", "PowerOff") %}
            -1
          {% elif is_state("input_select.remote_living_room", "Shield") %}
            33952374
          {% elif is_state("input_select.remote_living_room", "Broadcast TV") %}
            33952418
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.remote_living_room
      data_template:
        option: Select Activity

- alias: Harmony Living Room Off
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_living_room
    to: Power Off
  action:
    - service: remote.turn_off
      entity_id: remote.living_room
    - service: input_select.select_option
      entity_id: input_select.remote_living_room
      data_template:
        option: Select Activity

- alias: Harmony Family Room Activity
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_family_room
    from: Select Activity
  action:
    - service: remote.turn_on
      entity_id: remote.family_room
      data_template:
        activity: >
          {% if is_state("input_select.remote_family_room", "PowerOff") %}
            -1
          {% elif is_state("input_select.remote_family_room", "Gaming PC") %}
            34027083
          {% elif is_state("input_select.remote_family_room", "Roku") %}
            34027794
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.remote_family_room
      data_template:
        option: Select Activity

- alias: Harmony Family Room Off
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_family_room
    to: Power Off
  action:
    - service: remote.turn_off
      entity_id: remote.family_room
    - service: input_select.select_option
      entity_id: input_select.remote_family_room
      data_template:
        option: Select Activity

- alias: Harmony Bedroom Activity
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_bedroom
    from: Select Activity
  action:
    - service: remote.turn_on
      entity_id: remote.bedroom
      data_template:
        activity: >
          {% if is_state("input_select.remote_bedroom", "PowerOff") %}
            -1
          {% elif is_state("input_select.remote_bedroom", "Shield") %}
            28124049
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.remote_bedroom
      data_template:
        option: Select Activity

- alias: Harmony Bedroom Off
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.remote_bedroom
    to: Power Off
  action:
    - service: remote.turn_off
      entity_id: remote.bedroom
    - service: input_select.select_option
      entity_id: input_select.remote_bedroom
      data_template:
        option: Select Activity
