###########################################################
# Media Player: Onkyo 
###########################################################

- platform: onkyo
  host: !secret media_player_onkyo_host
  sources:
    tv-cd: "TV"
