###########################################################
# Media Player: Plex
# https://home-assistant.io/components/media_player.plex/
###########################################################

- platform: plex
  entity_namespace: 'plex'
