###########################################################
# Media Player: Roku
# https://home-assistant.io/components/media_player.roku/
###########################################################

- platform: roku
