###########################################################
# Media Player: Roku
# https://home-assistant.io/components/media_player.roku/
###########################################################

- platform: roku
  host: !secret media_player_roku_host
