###########################################################
# Notify
###########################################################

- platform: joaoapps_join
  name: phone_user2
  device_id: !secret notify_join_phone_user2_device_id
  api_key: !secret notify_join_api_key_j

- platform: joaoapps_join
  name: phone_user1
  device_id: !secret notify_join_phone_user1_device_id
  api_key: !secret notify_join_api_key_a

# - platform: kodi
#   name: kodi_htpc
#   host: !secret media_player_kodi_htpc_host
