###########################################################
# Notify
###########################################################

- platform: joaoapps_join
  name: phone_user1
  device_id: !secret notify_join_phone_user1_device_id
  api_key: !secret notify_join_api_key_user1

- platform: joaoapps_join
  name: phone_user2
  device_id: !secret notify_join_phone_user2_device_id
  api_key: !secret notify_join_api_key_user2
