###########################################################
# Remote
###########################################################

- platform: harmony
  name: Living Room
  activity: Shield
  host: !secret remote_harmony_living_room_host

- platform: harmony
  name: Bedroom
  activity: Shield
  host: !secret remote_harmony_bedroom_host
