###########################################################
# Package: Delivery
#   Automation is located in the automation directory
###########################################################

homeassistant:
  customize:
    group.delivery:
      custom_ui_state_card: state-card-custom-ui

    group.delivery_badges:
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: badges

    # camera.usps_mail:
    #   friendly_name: Mail Preview
    #   icon: mdi:email-outline

    sensor.packages_in_transit:
      icon: mdi:truck-delivery

    sensor.packages_out_for_delivery:
      icon: mdi:package

    sensor.packages_delivered:
      icon: mdi:package-variant

    # sensor.fedex:
    #   friendly_name: FexEx
    #   icon: mdi:package-variant-closed
    #   unit_of_measurement: boxes

    sensor.ups:
      friendly_name: UPS
      icon: mdi:package-variant-closed
      unit_of_measurement: boxes

    # sensor.usps_mail:
    #   friendly_name: Mail
    #   icon: mdi:mailbox

    # sensor.usps_packages:
    #   friendly_name: USPS
    #   icon: mdi:package-variant-closed
    #   unit_of_measurement: boxes

# usps:
#   driver: phantomjs
#   username: !secret usps_username
#   password: !secret usps_password

# camera:
#   - platform: usps
#     scan_interval: 5

group:
  delivery:
    name: Deliveries & Mail
    control: hidden
    icon: mdi:package-variant
    entities:
      - sensor.packages_in_transit
      - sensor.packages_out_for_delivery
      - sensor.packages_delivered
      # - camera.usps_mail
      - group.delivery_badges

  delivery_badges:
    name: Delivery Badges
    control: hidden
    icon: mdi:package-variant
    entities:
      # - sensor.usps_mail
      # - sensor.usps_packages
      # - sensor.fedex
      - sensor.ups

sensor:
  # - platform: fedex
  #   username: !secret fedex_username
  #   password: !secret fedex_password

  - platform: ups
    username: !secret ups_username
    password: !secret ups_password

  - platform: template
    sensors:
      packages_in_transit:
        friendly_name: In Transit
        unit_of_measurement: boxes
        value_template: >
          {% macro in_transit(sensor) %}
            {% if sensor.state %}
              {{ sensor.state | int - delivered(sensor) | int - out_for_delivery(sensor) | int }}
            {% else %}
              0
            {% endif %}
          {% endmacro %}
          {% macro out_for_delivery(sensor) %}
            {% if sensor.state and 'out_for_delivery' in sensor.attributes %}
              {{ sensor.attributes.out_for_delivery }}
            {% else %}
              0
            {% endif %}
          {% endmacro %}
          {% macro delivered(sensor) %}
            {% if sensor.state and 'delivered' in sensor.attributes %}
              {{ sensor.attributes.delivered }}
            {% else %}
              0
            {% endif %}
          {% endmacro %}
          {{ in_transit(states.sensor.usps_packages) | int + in_transit(states.sensor.fedex) | int + in_transit(states.sensor.ups) | int }}

      packages_out_for_delivery:
        friendly_name: Out for Delivery
        unit_of_measurement: boxes
        value_template: >
          {% macro out_for_delivery(sensor) %}
            {% if sensor.state and 'out_for_delivery' in sensor.attributes %}
              {{ sensor.attributes.out_for_delivery }}
            {% else %}
              0
            {% endif %}
          {% endmacro %}
          {{ out_for_delivery(states.sensor.usps_packages) | int + out_for_delivery(states.sensor.fedex) | int + out_for_delivery(states.sensor.ups) | int }}

      packages_delivered:
        friendly_name: Delivered
        unit_of_measurement: boxes
        value_template: >
          {% macro delivered(sensor) %}
            {% if sensor.state and 'delivered' in sensor.attributes %}
              {{ sensor.attributes.delivered }}
            {% else %}
              0
            {% endif %}
          {% endmacro %}
          {{ delivered(states.sensor.usps_packages) | int + delivered(states.sensor.fedex) | int + delivered(states.sensor.ups) | int }}
