###########################################################
# Package: Device Tracker
###########################################################

homeassistant:
  customize:
    device_tracker.oneplus_6:
      friendly_name: !secret name_user1

    device_tracker.galaxys9:
      friendly_name: !secret name_user2

    device_tracker.lg_v30:
      friendly_name: !secret name_user3

    group.people:
      custom_ui_state_card: state-card-custom-ui

    group.people_badges:
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: badges

  customize_glob:
    "sensor.device_":
      custom_ui_state_card: state-card-custom-ui
      templates:
        theme: "if (state == 'Online') return 'info_green'; else return 'info_red';"

device_tracker:
  - platform: unifi
    host: !secret device_tracker_unifi_host
    username: !secret device_tracker_unifi_username
    password: !secret device_tracker_unifi_password
    verify_ssl: false
    track_new_devices: false
    interval_seconds: 2
    consider_home: 180

group:
  people:
    name: People
    icon: mdi:account-multiple
    entities:
      - group.people_badges

  people_badges:
    name: People Badges
    icon: mdi:account-multiple
    entities:
      - device_tracker.galaxys9
      - device_tracker.oneplus_6
      - device_tracker.lg_v30

  devices_view:
    name: Devices
    view: yes
    icon: mdi:cloud-check
    entities:
      - group.devices
      - group.devices_computers
      - group.devices_portable
      - group.devices_media

  devices:
    name: Devices
    entities:
      - sensor.device_echo_dot_family_room
      - sensor.device_echo_dot_living_room
      - sensor.device_echo_dot_office
      - sensor.device_ecobee
      - sensor.device_harmony_bedroom
      - sensor.device_harmony_living_room
      - sensor.device_harmony_family_room
      - sensor.device_epson_workforce_845
      - sensor.device_samsung_ml2525w
      - sensor.device_opengarage
      - sensor.device_rachio

  devices_computers:
    name: Computers
    entities:
      - sensor.device_nasya
      - sensor.device_macbook
      - sensor.device_pennypc
      - sensor.device_athos
      - sensor.device_erebus

  devices_portable:
    name: Portable Devices
    entities:
      - sensor.device_kindle
      - sensor.device_kindle_hd8
      - sensor.device_kindle_hdx
      - sensor.device_leappad
      - sensor.device_mtcd_mazda
      - sensor.device_samsung_galaxy_camera

  devices_media:
    name: Media Players
    entities:
      - sensor.device_shield_living_room
      - sensor.device_shield_bedroom
      - sensor.device_mechanixcast
      - sensor.device_roku_hd
      - sensor.device_sony_tv
      - sensor.device_tcl_tv

sensor:
  - platform: template
    sensors:
      device_athos:
        friendly_name: Athos
        value_template: "{{ 'Online' if is_state('device_tracker.athos', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:desktop-tower' if is_state('device_tracker.athos', 'home') else 'mdi:blur-off' }}"

      device_erebus:
        friendly_name: Erebus
        value_template: "{{ 'Online' if is_state('device_tracker.erebus', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:desktop-tower' if is_state('device_tracker.erebus', 'home') else 'mdi:blur-off' }}"

      device_mechanixcast:
        friendly_name: MechanixCast
        value_template: "{{ 'Online' if is_state('device_tracker.mechanixcast', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:cast' if is_state('device_tracker.mechanixcast', 'home') else 'mdi:cast-off' }}"

      device_echo_dot_family_room:
        friendly_name: Echo Dot Family Room
        value_template: "{{ 'Online' if is_state('device_tracker.echo_dot_family_room', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:amazon-alexa' if is_state('device_tracker.echo_dot_family_room', 'home') else 'mdi:blur-off' }}"

      device_echo_dot_living_room:
        friendly_name: Echo Dot Living Room
        value_template: "{{ 'Online' if is_state('device_tracker.echo_dot_living_room', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:amazon-alexa' if is_state('device_tracker.echo_dot_living_room', 'home') else 'mdi:blur-off' }}"

      device_echo_dot_office:
        friendly_name: Echo Dot Office
        value_template: "{{ 'Online' if is_state('device_tracker.echo_dot_office', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:amazon-alexa' if is_state('device_tracker.echo_dot_office', 'home') else 'mdi:blur-off' }}"

      device_ecobee:
        friendly_name: Ecobee
        value_template: "{{ 'Online' if is_state('device_tracker.ecobee', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:thermostat' if is_state('device_tracker.ecobee', 'home') else 'mdi:blur-off' }}"

      device_epson_workforce_845:
        friendly_name: Epson Workforce 845
        value_template: "{{ 'Online' if is_state('device_tracker.epson_workforce_845', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:printer' if is_state('device_tracker.epson_workforce_845', 'home') else 'mdi:blur-off' }}"

      device_harmony_bedroom:
        friendly_name: Harmony Bedroom
        value_template: "{{ 'Online' if is_state('device_tracker.harmony_bedroom', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:remote' if is_state('device_tracker.harmony_bedroom', 'home') else 'mdi:blur-off' }}"

      device_harmony_living_room:
        friendly_name: Harmony Living Room
        value_template: "{{ 'Online' if is_state('device_tracker.harmony_living_room', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:remote' if is_state('device_tracker.harmony_living_room', 'home') else 'mdi:blur-off' }}"

      device_harmony_family_room:
        friendly_name: Harmony Family Room
        value_template: "{{ 'Online' if is_state('device_tracker.harmony_family_room', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:remote' if is_state('device_tracker.harmony_family_room', 'home') else 'mdi:blur-off' }}"

      device_kindle:
        friendly_name: Kindle
        value_template: "{{ 'Online' if is_state('device_tracker.kindle', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:tablet' if is_state('device_tracker.kindle', 'home') else 'mdi:blur-off' }}"

      device_kindle_hd8:
        friendly_name: Kindle Fire HD8
        value_template: "{{ 'Online' if is_state('device_tracker.kindle_hd8', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:tablet' if is_state('device_tracker.kindle_hd8', 'home') else 'mdi:blur-off' }}"

      device_kindle_hdx:
        friendly_name: Kindle Fire HDX
        value_template: "{{ 'Online' if is_state('device_tracker.kindle_hdx', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:tablet' if is_state('device_tracker.kindle_hdx', 'home') else 'mdi:blur-off' }}"

      device_leappad:
        friendly_name: LeapPad
        value_template: "{{ 'Online' if is_state('device_tracker.leappad', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:tablet' if is_state('device_tracker.leappad', 'home') else 'mdi:blur-off' }}"

      device_mtcd_mazda:
        friendly_name: MTCD [Mazda]
        value_template: "{{ 'Online' if is_state('device_tracker.mtcd_mazda', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:car-connected' if is_state('device_tracker.mtcd_mazda', 'home') else 'mdi:blur-off' }}"

      device_nasya:
        friendly_name: Nasya
        value_template: "{{ 'Online' if is_state('device_tracker.nasya', 'home') or is_state('device_tracker.nasya_wifi', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:laptop' if is_state('device_tracker.nasya', 'home') or is_state('device_tracker.nasya_wifi', 'home') else 'mdi:laptop-off' }}"

      device_opengarage:
        friendly_name: OpenGarage
        value_template: "{{ 'Online' if is_state('device_tracker.opengarage', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:garage' if is_state('device_tracker.opengarage', 'home') else 'mdi:blur-off' }}"

      device_pennypc:
        friendly_name: Penny PC
        value_template: "{{ 'Online' if is_state('device_tracker.pennypc', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:laptop' if is_state('device_tracker.pennypc', 'home') else 'mdi:laptop-off' }}"

      device_shield_bedroom:
        friendly_name: Shield [Bedroom]
        value_template: "{{ 'Online' if is_state('device_tracker.shield_bedroom', 'home') or is_state('device_tracker.shield_wifi_bedroom', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:cast' if is_state('device_tracker.shield_bedroom', 'home') or is_state('device_tracker.shield_wifi_bedroom', 'home') else 'mdi:cast-off' }}"

      device_shield_living_room:
        friendly_name: Shield [Living Room]
        value_template: "{{ 'Online' if is_state('device_tracker.shield_living_room', 'home') or is_state('device_tracker.shield_wifi_living_room', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:cast' if is_state('device_tracker.shield_living_room', 'home') or is_state('device_tracker.shield_wifi_living_room', 'home') else 'mdi:cast-off' }}"

      device_rachio:
        friendly_name: Rachio
        value_template: "{{ 'Online' if is_state('device_tracker.rachio', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:water-pump' if is_state('device_tracker.rachio', 'home') else 'mdi:blur-off' }}"

      device_roku_hd:
        friendly_name: Roku HD
        value_template: "{{ 'Online' if is_state('device_tracker.roku_hd__785', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:play-box-outline' if is_state('device_tracker.roku_hd__785', 'home') else 'mdi:blur-off' }}"

      device_macbook:
        friendly_name: MacBook
        value_template: "{{ 'Online' if is_state('device_tracker.macbook', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:laptop-mac' if is_state('device_tracker.macbook', 'home') else 'mdi:laptop-off' }}"

      device_samsung_galaxy_camera:
        friendly_name: Samsung Galaxy Camera
        value_template: "{{ 'Online' if is_state('device_tracker.samsung_galaxy_camera', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:camera' if is_state('device_tracker.samsung_galaxy_camera', 'home') else 'mdi:camera-off' }}"

      device_samsung_ml2525w:
        friendly_name: Samsung ML-2525w
        value_template: "{{ 'Online' if is_state('device_tracker.samsung_ml2525w', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:printer' if is_state('device_tracker.samsung_ml2525w', 'home') else 'mdi:blur-off' }}"

      device_sony_tv:
        friendly_name: Sony TV
        value_template: "{{ 'Online' if is_state('device_tracker.sony_tv', 'home') or is_state('device_tracker.sony_tv_wifi', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:television' if is_state('device_tracker.sony_tv', 'home') or is_state('device_tracker.sony_tv_wifi', 'home') else 'mdi:television-off' }}"

      device_tcl_tv:
        friendly_name: TCL TV
        value_template: "{{ 'Online' if is_state('device_tracker.tcl_tv', 'home') or is_state('device_tracker.tcl_tv_wifi', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:television' if is_state('device_tracker.tcl_tv', 'home') or is_state('device_tracker.tcl_tv_wifi', 'home') else 'mdi:television-off' }}"
