###########################################################
# Package: Doors
#   Automation is located in the automation directory
###########################################################

homeassistant:
  customize:
    sensor.door_front:
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: false
      extra_data_template: >
        ${entities['sensor.door_front_battery_level'].state !== 0 ? (entities['sensor.door_front_battery_level'].state + '%') : ''}

    sensor.door_garage_entry:
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: false
      extra_data_template: >
        ${entities['sensor.door_garage_entry_battery_level'].state !== 0 ? (entities['sensor.door_garage_entry_battery_level'].state + '%') : ''}

    sensor.door_garage_outside:
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: false
      extra_data_template: >
        ${entities['sensor.door_garage_outside_battery_level'].state !== 0 ? (entities['sensor.door_garage_outside_battery_level'].state + '%') : ''}

    sensor.door_back:
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: false
      extra_data_template: >
        ${entities['sensor.door_back_battery_level'].state !== 0 ? (entities['sensor.door_back_battery_level'].state + '%') : ''}

  customize_glob:
    "binary_sensor.door_*_sensor":
      hidden: true
    "sensor.door_*_alarm_level":
      hidden: true
    "sensor.door_*_alarm_type":
      hidden: true
    "sensor.door_*_burglar":
      hidden: true
    "sensor.door_*_sourcenodeid":
      hidden: true

    "sensor.door_*":
      custom_ui_state_card: state-card-custom-ui
      templates:
        theme: "if (state == 'Closed') return 'info_green'; else return 'alert_red';"

    "zwave.door_*":
      icon: mdi:door

recorder:
  exclude:
    entities:
      - binary_sensor.door_front_sensor
      - sensor.door_front_alarm_level
      - sensor.door_front_alarm_type
      - sensor.door_front_burglar
      - sensor.door_front_sourcenodeid

      - binary_sensor.door_garage_entry_sensor
      - sensor.door_garage_entry_alarm_level
      - sensor.door_garage_entry_alarm_type
      - sensor.door_garage_entry_burglar
      - sensor.door_garage_entry_sourcenodeid

      - binary_sensor.door_back_sensor
      - sensor.door_back_alarm_level
      - sensor.door_back_alarm_type
      - sensor.door_back_burglar
      - sensor.door_back_sourcenodeid

      - binary_sensor.door_garage_outside_sensor
      - sensor.door_garage_outside_alarm_level
      - sensor.door_garage_outside_alarm_type
      - sensor.door_garage_outside_burglar
      - sensor.door_garage_outside_sourcenodeid

influxdb:
  exclude:
    entities:
      - binary_sensor.door_front_sensor
      - sensor.door_front_alarm_level
      - sensor.door_front_alarm_type
      - sensor.door_front_burglar
      - sensor.door_front_sourcenodeid

      - binary_sensor.door_garage_entry_sensor
      - sensor.door_garage_entry_alarm_level
      - sensor.door_garage_entry_alarm_type
      - sensor.door_garage_entry_burglar
      - sensor.door_garage_entry_sourcenodeid

      - binary_sensor.door_back_sensor
      - sensor.door_back_alarm_level
      - sensor.door_back_alarm_type
      - sensor.door_back_burglar
      - sensor.door_back_sourcenodeid

      - binary_sensor.door_garage_outside_sensor
      - sensor.door_garage_outside_alarm_level
      - sensor.door_garage_outside_alarm_type
      - sensor.door_garage_outside_burglar
      - sensor.door_garage_outside_sourcenodeid

group:
  doors:
    name: Doors
    entities:
      - sensor.door_front
      - sensor.door_back
      - sensor.door_garage_entry
      - sensor.door_garage_outside

sensor:
  - platform: template
    sensors:
      door_front:
        friendly_name: Front Door
        value_template: >-
          {%- if is_state("sensor.door_front_alarm_level", "255") -%}
            {%- if is_state("sensor.door_front_burglar", "3") -%}
              Tampered
            {%- else -%}
              Open
            {%- endif %}
          {%- else -%}
            Closed
          {%- endif %}
        icon_template: >
          {%- if is_state("sensor.door_front_alarm_level", "255") -%}
            {%- if is_state("sensor.door_front_burglar", "3") -%}
              mdi:alert
            {%- else -%}
              mdi:door-open
            {%- endif %}
          {%- else -%}
            mdi:door
          {%- endif %}

      door_garage_entry:
        friendly_name: Garage Entry Door
        value_template: >-
          {%- if is_state("sensor.door_garage_entry_alarm_level", "255") -%}
            {%- if is_state("sensor.door_garage_entry_burglar", "3") -%}
              Tampered
            {%- else -%}
              Open
            {%- endif %}
          {%- else -%}
            Closed
          {%- endif %}
        icon_template: >
          {%- if is_state("sensor.door_garage_entry_alarm_level", "255") -%}
            {%- if is_state("sensor.door_garage_entry_burglar", "3") -%}
              mdi:alert
            {%- else -%}
              mdi:door-open
            {%- endif %}
          {%- else -%}
            mdi:door
          {%- endif %}

      door_garage_outside:
        friendly_name: Garage Outside Door
        value_template: >-
          {%- if is_state("sensor.door_garage_outside_alarm_level", "255") -%}
            {%- if is_state("sensor.door_garage_outside_burglar", "3") -%}
              Tampered
            {%- else -%}
              Open
            {%- endif %}
          {%- else -%}
            Closed
          {%- endif %}
        icon_template: >
          {%- if is_state("sensor.door_garage_outside_alarm_level", "255") -%}
            {%- if is_state("sensor.door_garage_outside_burglar", "3") -%}
              mdi:alert
            {%- else -%}
              mdi:door-open
            {%- endif %}
          {%- else -%}
            mdi:door
          {%- endif %}

      door_back:
        friendly_name: Sliding Door
        value_template: >-
          {%- if is_state("sensor.door_back_alarm_level", "255") -%}
            {%- if is_state("sensor.door_back_burglar", "3") -%}
              Tampered
            {%- else -%}
              Open
            {%- endif %}
          {%- else -%}
            Closed
          {%- endif %}
        icon_template: >
          {%- if is_state("sensor.door_back_alarm_level", "255") -%}
            {%- if is_state("sensor.door_back_burglar", "3") -%}
              mdi:alert
            {%- else -%}
              mdi:door-open
            {%- endif %}
          {%- else -%}
            mdi:door
          {%- endif %}
