###########################################################
# Package: Dreamscreen
# Component: https://github.com/GregoryDosh/Home-Assistant-DreamScreen-Service
###########################################################

dreamscreen:

automation:
  - alias: "[DS - Family Room] Harmony Reactive Activity"
    trigger:
      - platform: state
        entity_id: sensor.remote_family_room
    condition:
      - condition: or
        conditions:
        - condition: state
          entity_id: sensor.remote_family_room
          state: "Computer"
        - condition: state
          entity_id: sensor.remote_family_room
          state: "PS3"
        - condition: state
          entity_id: sensor.remote_family_room
          state: "XBox"
    action:
      - service: dreamscreen.set_mode
        data:
          entity_id: dreamscreen.family_room
          mode: 1

  - alias: "[DS - Family Room] Harmony Ambiant Activity"
    trigger:
      - platform: state
        entity_id: sensor.remote_family_room
        to: "Roku"
    action:
      - service: dreamscreen.set_mode
        data:
          entity_id: dreamscreen.family_room
          mode: 3
      - service: dreamscreen.set_ambiance_color
        data:
          entity_id: dreamscreen.family_room
          color: "#331900"

  - alias: "[DS - Family Room] Harmony Power Off"
    trigger:
      - platform: state
        entity_id: sensor.remote_family_room
        to: "Power Off"
    action:
      - service: dreamscreen.set_mode
        data:
          entity_id: dreamscreen.family_room
          mode: 0
