###########################################################
# Package: Ecobee
###########################################################

homeassistant:
  customize:
    climate.home:
      friendly_name: Ecobee
      icon: mdi:thermostat

    group.climate:
      custom_ui_state_card: state-card-custom-ui

    group.climate_badges:
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: badges

    sensor.kitchen_temperature:
      friendly_name: Kitchen
      icon: mdi:thermometer

    sensor.family_room_temperature:
      friendly_name: Family Room
      icon: mdi:thermometer

    sensor.office_temperature:
      friendly_name: Office
      icon: mdi:thermometer

    sensor.emma_temperature:
      friendly_name: "Emma's Room"
      icon: mdi:thermometer

    sensor.ethan_temperature:
      friendly_name: "Ethan's Room"
      icon: mdi:thermometer

    sensor.house_thermostat_away_mode:
      friendly_name: Ecobee Away Mode

    sensor.home_humidity:
      friendly_name: Ecobee Humidity
      icon: mdi:water-percent

    sensor.home_temperature:
      friendly_name: Home
      icon: mdi:thermometer
      hidden: true

  customize_glob:
    "binary_sensor.*_occupancy":
      hidden: true

    "sensor.occupancy_*":
      custom_ui_state_card: state-card-custom-ui
      templates:
        theme: "if (state == 'Occupied') return 'info_green'; else return 'alert_red';"

ecobee:
  api_key: !secret ecobee_api_key

climate:
  platform: ecobee

group:
  climate:
    name: Climate
    control: hidden
    icon: mdi:thermostat
    entities:
      - climate.home
      - sensor.house_thermostat_away_mode
      - sensor.home_humidity
      - group.climate_badges

  climate_badges:
    name: Climate Badges
    control: hidden
    icon: mdi:thermostat
    entities:
      - sensor.kitchen_temperature
      - sensor.emma_temperature
      - sensor.ethan_temperature
      - sensor.family_room_temperature
      - sensor.office_temperature

  occupancy:
    name: Occupancy
    entities:
      - sensor.occupancy_home
      - sensor.occupancy_kitchen
      - sensor.occupancy_family_room
      - sensor.occupancy_office
      - sensor.occupancy_emma
      - sensor.occupancy_ethan

sensor:
  - platform: template
    sensors:
      house_thermostat_away_mode:
        value_template: >-
          {%- if is_state_attr('climate.home', 'away_mode', 'on') -%}
            Away
          {%- else -%}
            Home
          {%- endif %}
        icon_template: >
          {%- if is_state_attr('climate.home', 'away_mode', 'on') -%}
            mdi:walk
          {%- else %}
            mdi:home
          {%- endif %}

      occupancy_home:
        friendly_name: Home Occupancy
        value_template: >-
          {%- if is_state("binary_sensor.home_occupancy", "on") -%}
            Occupied
          {%- else -%}
            Clear
          {%- endif %}
        icon_template: >
          {%- if is_state("binary_sensor.home_occupancy", "on") -%}
            mdi:account
          {%- else -%}
            mdi:account-off
          {%- endif %}

      occupancy_emma:
        friendly_name: "Emma's Room Occupancy"
        value_template: >-
          {%- if is_state("binary_sensor.emma_occupancy", "on") -%}
            Occupied
          {%- else -%}
            Clear
          {%- endif %}
        icon_template: >
          {%- if is_state("binary_sensor.emma_occupancy", "on") -%}
            mdi:account
          {%- else -%}
            mdi:account-off
          {%- endif %}

      occupancy_ethan:
        friendly_name: "Ethan's Room Occupancy"
        value_template: >-
          {%- if is_state("binary_sensor.ethan_occupancy", "on") -%}
            Occupied
          {%- else -%}
            Clear
          {%- endif %}
        icon_template: >
          {%- if is_state("binary_sensor.ethan_occupancy", "on") -%}
            mdi:account
          {%- else -%}
            mdi:account-off
          {%- endif %}

      occupancy_family_room:
        friendly_name: Family Room Occupancy
        value_template: >-
          {%- if is_state("binary_sensor.family_room_occupancy", "on") -%}
            Occupied
          {%- else -%}
            Clear
          {%- endif %}
        icon_template: >
          {%- if is_state("binary_sensor.family_room_occupancy", "on") -%}
            mdi:account
          {%- else -%}
            mdi:account-off
          {%- endif %}

      occupancy_kitchen:
        friendly_name: Kitchen Occupancy
        value_template: >-
          {%- if is_state("binary_sensor.kitchen_occupancy", "on") -%}
            Occupied
          {%- else -%}
            Clear
          {%- endif %}
        icon_template: >
          {%- if is_state("binary_sensor.kitchen_occupancy", "on") -%}
            mdi:account
          {%- else -%}
            mdi:account-off
          {%- endif %}

      occupancy_office:
        friendly_name: Office Occupancy
        value_template: >-
          {%- if is_state("binary_sensor.office_occupancy", "on") -%}
            Occupied
          {%- else -%}
            Clear
          {%- endif %}
        icon_template: >
          {%- if is_state("binary_sensor.office_occupancy", "on") -%}
            mdi:account
          {%- else -%}
            mdi:account-off
          {%- endif %}
