###########################################################
# Package: Garage
###########################################################

cover:
  - platform: opengarage
    covers:
      garage:
        host: !secret cover_opengarage_host
        device_key: !secret cover_opengarage_device_key
        name: Garage Door

recorder:
  exclude:
    entities:
    - sensor.garage_door_status

influxdb:
  exclude:
    entities:
    - sensor.garage_door_status

sensor:
  - platform: template
    sensors:
      garage_door_status:
        friendly_name: Status
        value_template: >-
          {% if states.cover.garage_door %}
            {% if states.cover.garage_door.attributes["door_state"] == "open" %}
              Open
            {% elif states.cover.garage_door.attributes["door_state"] == "closed" %}
              Closed
            {% elif states.cover.garage_door.attributes["door_state"] == "opening" %}
              Opening
            {% elif states.cover.garage_door.attributes["door_state"] == "closing" %}
              Closing
            {% else %}
              Unknown
            {% endif %}
          {% else %}
            Offline
          {% endif %}

      garage_car_present:
        friendly_name: Car in Garage
        value_template: >-
          {% if states.cover.garage_door %}
            {% if states.cover.garage_door.attributes["distance_sensor"] == "offline" %}
              Offline
            {% elif states.cover.garage_door.state == "open" %}
              Door Open
            {% elif ((states.cover.garage_door.attributes["distance_sensor"] > 50) and (states.cover.garage_door.attributes["distance_sensor"] < 170)) %}
              Yes
            {% else %}
              No
            {% endif %}
          {% else %}
            Offline
          {% endif %}
        icon_template: >
          {% if states.cover.garage_door %}
            {% if states.cover.garage_door.attributes["distance_sensor"] == "offline" %}
              mdi:cancel
            {% elif states.cover.garage_door.state == "open" %}
              mdi:garage-open
            {% elif ((states.cover.garage_door.attributes["distance_sensor"] > 50) and (states.cover.garage_door.attributes["distance_sensor"] < 170)) %}
              mdi:car
            {% else %}
              mdi:close-circle-outline
            {% endif %}
          {% else %}
            mdi:cancel
          {% endif %}

automation:
  - alias: "[Notify] Garage Door Left Open and Leaving"
    trigger:
      - platform: state
        entity_id: group.people
        to: "not_home"
    condition:
      - condition: state
        entity_id: cover.garage_door
        state: "open"
    action:
      - service: notify.join_users
        data_template:
          title: Garage Door Open
          message: "The garage door was left open when you left! Close it!"
          data:
            icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/garage-open.png"
            smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

  - alias: "[Notify] Garage Door Opened and Away"
    trigger:
      - platform: state
        entity_id: cover.garage_door
        to: "open"
    condition:
      - condition: state
        entity_id: group.people
        state: "not_home"
    action:
      - service: notify.join_users
        data_template:
          title: Garage Door Open
          message: "The garage door opened and no one is home."
          data:
            icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/garage-open.png"
            smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

  - alias: "[Notify] Garage Door Left Open"
    trigger:
      - platform: time
        minutes: "/30"
        seconds: "00"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: cover.garage_door
          state: "open"
        - condition: state
          entity_id: binary_sensor.garage_motion_sensor
          state: "off"
        - condition: template
          value_template: >
            {{ (as_timestamp(now()) - as_timestamp(states.cover.garage_door.last_changed)) / 60 > 45 }}
    action:
      - service: notify.join_all
        data_template:
          title: Garage Door Open
          message: >
            {% macro last_changed(entity) %}
            {% if entity.state %}
            {% set uptime = (as_timestamp(now()) - as_timestamp(entity.last_changed)) | int %}
            {% set minutes = ((uptime % 3600) / 60) | int %}
            {% set hours = ((uptime % 86400) / 3600) | int %}
            {% set days = (uptime / 86400) | int %}
            {%- if days > 0 -%}
            {{ days }} d
            {%- endif -%}
            {%- if hours > 0 -%}
            {%- if days > 0 -%}
            {{ ' ' }}
            {%- endif -%}
            {{ hours }}h
            {%- endif -%}
            {%- if minutes > 0 -%}
            {%- if hours > 0 -%}
            {{ ' ' }}
            {%- endif -%}
            {{ minutes }}min
            {%- endif -%}
            {%- endif -%}
            {% endmacro %}
            The {{ states.cover.garage_door.attributes.friendly_name }} has been open for {{ last_changed(states.cover.garage_door) }}.
          data:
            icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/garage-open.png"
            smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
      - service: tts.google_say
        entity_id: media_player.living_room_speaker
        data_template:
          message: >-
            {% macro last_changed(entity) %}
            {% if entity.state %}
            {% set uptime = (as_timestamp(now()) - as_timestamp(entity.last_changed)) | int %}
            {% set minutes = ((uptime % 3600) / 60) | int %}
            {% set hours = ((uptime % 86400) / 3600) | int %}
            {% set days = (uptime / 86400) | int %}
            {%- if days > 0 -%}
            {{ days }} d
            {%- endif -%}
            {%- if hours > 0 -%}
            {%- if days > 0 -%}
            {{ ' ' }}
            {%- endif -%}
            {{ hours }}h
            {%- endif -%}
            {%- if minutes > 0 -%}
            {%- if hours > 0 -%}
            {{ ' ' }}
            {%- endif -%}
            {{ minutes }}min
            {%- endif -%}
            {%- endif -%}
            {% endmacro %}
            Hey! The {{ states.cover.garage_door.attributes.friendly_name }} has been open for {{ last_changed(states.cover.garage_door) }}.
          cache: false
