###########################################################
# Package: Irrigation
###########################################################

homeassistant:
  customize:
    switch.1front_north:
      friendly_name: "[Zone 1] Front north"
      icon: mdi:water

    switch.2front_middle:
      friendly_name: "[Zone 2] Front middle"
      icon: mdi:water

    switch.3north_fence:
      friendly_name: "[Zone 3] North fence"
      icon: mdi:water

    switch.4back_middle_and_south:
      friendly_name: "[Zone 4] Back middle and South"
      icon: mdi:water

    switch.5back_south:
      friendly_name: "[Zone 5] Back south"
      icon: mdi:water

    switch.6front_south:
      friendly_name: "[Zone 6] Front south"
      icon: mdi:water

    switch.7flower_beds:
      friendly_name: "[Zone 7] Flower beds"
      icon: mdi:water

rachio:
  api_key: !secret rachio_api_key

group:
  irrigation:
    name: Irrigation
    icon: mdi:water-pump
    view: true
    entities:
    - group.rachio
  rachio:
    name: Rachio
    icon: mdi:water-pump
    entities:
    - switch.1front_north
    - switch.2front_middle
    - switch.3north_fence
    - switch.4back_middle_and_south
    - switch.5back_south
    - switch.6front_south
    - switch.7flower_beds
