###########################################################
# Package: Lights
###########################################################

homeassistant:
  customize_glob:
    "switch.*_light":
      icon: mdi:lightbulb

    "zwave.*_light":
      icon: mdi:lightbulb

  customize:
    zwave.living_room:
      icon: mdi:lightbulb

    zwave.kitchen:
      icon: mdi:lightbulb

    zwave.family_room:
      icon: mdi:lightbulb

    zwave.play_space:
      icon: mdi:lightbulb

    # zwave.lamp_left:
    #   icon: mdi:lamp

    # zwave.lamp_right:
    #   icon: mdi:lamp

group:
  lights_great_room:
    name: Great Room Lights
    entities:
      - light.living_room
      - switch.front_entry_light
      - switch.garage_entry_light
      - light.kitchen
      - switch.dining_room_light
      - switch.hallway_light
      # - light.lamp_left
      # - light.lamp_right

  lights_hallway:
    name: Hallway Lights
    entities:
      - switch.hallway_light
      - switch.basement_hallway_light

  lights_office:
    name: Office Lights
    entities:
      - light.office_lamp
      - light.office_light

  lights_basement:
    name: Basement Lights
    entities:
      - light.family_room
      - light.play_space
      - switch.basement_hallway_light

  # lights_theater:
  #   name: Theater Room Lights
  #   entities:
  #     - light.theater_room
  #     - light.theater_walls

  # lights_master_bedroom:
  #   name: Master Bedroom Lights
  #   entities:
  #     - light.bedroom_master

  # lights_bedroom_1:
  #   name: Bedroom 1 Lights
  #   entities:
  #     - switch.bedroom1_light

  # lights_bedroom_2:
  #   name: Bedroom 2 Lights
  #   entities:
  #     - switch.bedroom2_light

  # lights_bedroom_3:
  #   name: Bedroom 3 Lights
  #   entities:
  #     - switch.bedroom3_light

  # lights_bedroom_4:
  #   name: Bedroom 4 Lights
  #   entities:
  #     - switch.bedroom4_light

  lights_outside:
    name: Outside Lights
    entities:
      - switch.outside_front_light
      - switch.outside_side_light
      - switch.outside_back_light

  lights_inside:
    name: Inside Lights
    entities:
      - light.living_room
      - switch.front_entry_light
      - switch.garage_entry_light
      - light.kitchen
      - switch.dining_room_light
      - switch.hallway_light
      - switch.garage_light
      - switch.basement_hallway_light
      - light.family_room
      - light.play_space
      # - light.theater_room
      # - light.theater_walls
      # - light.bedroom_master
      # - switch.bedroom1_light
      # - switch.bedroom2_light
      # - switch.bedroom3_light
      # - switch.bedroom4_light

  all_lights:
    name: All Lights
    icon: mdi:lightbulb-on
    entities:
      - light.kitchen
      - switch.dining_room_light
      - light.living_room
      - switch.front_entry_light
      - switch.garage_entry_light
      # - light.lamp_left
      # - light.lamp_right
      - switch.hallway_light
      - switch.garage_light
      - light.office_lamp
      - light.office_light
      - switch.basement_hallway_light
      - light.family_room
      - light.play_space
      # - light.theater_room
      # - light.theater_walls
      # - light.bedroom_master
      # - switch.bedroom1_light
      # - switch.bedroom2_light
      # - switch.bedroom3_light
      # - switch.bedroom4_light
      - switch.outside_front_light
      - switch.outside_side_light
      - switch.outside_back_light

light:
  platform: group
  name: Office Light
  entities:
    - light.office_1
    - light.office_2
    - light.office_3

automation:
  - alias: "[Lights] Front on at Night"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:20:00"
    condition:
      - condition: time
        before: "22:30:00"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.outside_front_light

  - alias: "[Lights] Front off at Night"
    trigger:
      - platform: time
        at: "22:30:00"
    action:
      - service: homeassistant.turn_off
        entity_id: switch.outside_front_light

  - alias: "[Lights] Turn on when Arrive"
    trigger:
      - platform: state
        entity_id: group.people
        from: "not_home"
        to: "home"
    condition:
      - condition: sun
        after: sunset
        after_offset: "-0:30:00"
      - condition: time
        before: "23:59:59"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.garage_entry_light
      - service: light.turn_on
        entity_id: light.living_room
        data:
          brightness: 50
      - service: notify.join_users
        data_template:
          title: Welcome Home
          message: "The lights have been turned on."
          data:
            icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lightbulb-on.png"
            smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
      - delay: "00:10:00"
      - service: homeassistant.turn_off
        entity_id: switch.garage_entry_light

  - alias: "[Lights] Turn off when Away"
    trigger:
      - platform: state
        entity_id: group.people
        from: "home"
        to: "not_home"
        for:
          minutes: 10
    condition:
      - condition: sun
        after: sunrise
        after_offset: "00:45:00"
      - condition: sun
        before: sunset
        before_offset: "-00:45:00"
    action:
      - service: homeassistant.turn_off
        entity_id: group.all_lights
      - service: notify.join_users
        data_template:
          title: Lights Out
          message: "The lights have been turned off since no one is home."
          data:
            icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lightbulb.png"
            smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
