###########################################################
# Package: Lights
###########################################################

homeassistant:
  customize_glob:
    "light.*":
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      show_last_changed: false
      extra_data_template: >
        if (attributes.brightness) return Math.round(attributes.brightness / 2.55) + '%'; else return null;

  customize:
    zwave.living_room:
      icon: mdi:lightbulb

    zwave.kitchen:
      icon: mdi:lightbulb

    zwave.family_room:
      icon: mdi:lightbulb

    zwave.play_space:
      icon: mdi:lightbulb

    # zwave.lamp_left:
    #   icon: mdi:lamp

    # zwave.lamp_right:
    #   icon: mdi:lamp

    zwave.outside_front_light:
      icon: mdi:lightbulb

    zwave.outside_side_light:
      icon: mdi:lightbulb

    zwave.outside_back_light:
      icon: mdi:lightbulb

    zwave.garage_light:
      icon: mdi:lightbulb

    zwave.front_entry_light:
      icon: mdi:lightbulb

    zwave.garage_entry_light:
      icon: mdi:lightbulb

    zwave.dining_room_light:
      icon: mdi:lightbulb

    zwave.hallway_light:
      icon: mdi:lightbulb

    zwave.basement_hallway_light:
      icon: mdi:lightbulb

    # zwave.bedroom1_light:
    #   icon: mdi:lightbulb

    # zwave.bedroom2_light:
    #   icon: mdi:lightbulb

    # zwave.bedroom3_light:
    #   icon: mdi:lightbulb

    # zwave.bedroom4_light:
    #   icon: mdi:lightbulb

    light.living_room_level:
      friendly_name: Living Room Light
      slider_theme:
        min: 5
        max: 255
        pin: true
        off_when_min: false
        report_when_not_changed: false

    light.kitchen_level:
      friendly_name: Kitchen Light
      slider_theme:
        min: 5
        max: 255
        pin: true
        off_when_min: false
        report_when_not_changed: false

    light.family_room_level:
      friendly_name: Family Room Light
      slider_theme:
        min: 16
        max: 255
        pin: true
        off_when_min: false
        report_when_not_changed: false

    light.play_space_level:
      friendly_name: Play Space Light
      slider_theme:
        min: 16
        max: 255
        pin: true
        off_when_min: false
        report_when_not_changed: false

    # light.lamp_left_level:
    #   friendly_name: Living Room Lamp
    #   icon: mdi:lamp
    #   slider_theme:
    #     min: 5
    #     max: 255
    #     pin: true
    #     off_when_min: false
    #     report_when_not_changed: false

    # light.lamp_right_level:
    #   friendly_name: Living Room Lamp
    #   icon: mdi:lamp
    #   slider_theme:
    #     min: 5
    #     max: 255
    #     pin: true
    #     off_when_min: false
    #     report_when_not_changed: false

    switch.outside_front_light_switch:
      friendly_name: Front Light
      icon: mdi:lightbulb

    switch.outside_side_light_switch:
      friendly_name: Side Light
      icon: mdi:lightbulb

    switch.outside_back_light_switch:
      friendly_name: Back Light
      icon: mdi:lightbulb

    switch.garage_light_switch:
      friendly_name: Garage Light
      icon: mdi:lightbulb

    switch.front_entry_light_switch:
      friendly_name: Entry Light
      icon: mdi:lightbulb

    switch.garage_entry_light_switch:
      friendly_name: Garage Entry Light
      icon: mdi:lightbulb

    switch.dining_room_light_switch:
      friendly_name: Dining Room Light
      icon: mdi:lightbulb

    switch.hallway_light_switch:
      friendly_name: Hallway Light
      icon: mdi:lightbulb

    switch.basement_hallway_light_switch:
      friendly_name: Basement Hallway Light
      icon: mdi:lightbulb

    # switch.bedroom1_light_switch:
    #   friendly_name: Bedroom 1 Light
    #   icon: mdi:lightbulb

    # switch.bedroom2_light_switch:
    #   friendly_name: Bedroom 2 Light
    #   icon: mdi:lightbulb

    # switch.bedroom3_light_switch:
    #   friendly_name: Bedroom 3 Light
    #   icon: mdi:lightbulb

    # switch.bedroom4_light_switch:
    #   friendly_name: Bedroom 4 Light
    #   icon: mdi:lightbulb

group:
  lights_view:
    name: Lights
    view: yes
    icon: mdi:lightbulb
    entities:
      - group.lights_great_room
      - group.lights_hallway
      - group.lights_basement
      - group.lights_inside
      - group.lights_outside

  lights_great_room:
    name: Great Room Lights
    entities:
      - light.living_room_level
      - light.kitchen_level
      - switch.dining_room_light_switch
      - switch.front_entry_light_switch
      - switch.garage_entry_light_switch
      - switch.hallway_light_switch
      # - light.lamp_left_level
      # - light.lamp_right_level

  lights_hallway:
    name: Hallway Lights
    entities:
      - switch.hallway_light_switch
      - switch.basement_hallway_light_switch

  lights_basement:
    name: Basement Lights
    entities:
      - light.family_room_level
      - light.play_space_level
      - switch.basement_hallway_light_switch

  # lights_theater:
  #   name: Theater Room Lights
  #   entities:
  #     - light.theater_room_level
  #     - light.theater_walls_level

  # lights_master_bedroom:
  #   name: Master Bedroom Lights
  #   entities:
  #     - light.bedroom_master_level

  # lights_bedroom_1:
  #   name: Bedroom 1 Lights
  #   entities:
  #     - switch.bedroom1_light_switch

  # lights_bedroom_2:
  #   name: Bedroom 2 Lights
  #   entities:
  #     - switch.bedroom2_light_switch

  # lights_bedroom_3:
  #   name: Bedroom 3 Lights
  #   entities:
  #     - switch.bedroom3_light_switch

  # lights_bedroom_4:
  #   name: Bedroom 4 Lights
  #   entities:
  #     - switch.bedroom4_light_switch

  lights_outside:
    name: Outside Lights
    entities:
      - switch.outside_front_light_switch
      - switch.outside_side_light_switch
      - switch.outside_back_light_switch

  lights_inside:
    name: Inside Lights
    entities:
      - light.living_room_level
      - light.kitchen_level
      - switch.front_entry_light_switch
      - switch.garage_entry_light_switch
      - switch.dining_room_light_switch
      - switch.hallway_light_switch
      - switch.basement_hallway_light_switch
      - switch.garage_light_switch
      - light.family_room_level
      - light.play_space_level
      # - light.theater_room_level
      # - light.theater_walls_level
      # - light.bedroom_master_level
      # - switch.bedroom1_light_switch
      # - switch.bedroom2_light_switch
      # - switch.bedroom3_light_switch
      # - switch.bedroom4_light_switch

  all_light_switches:
    name: All Light Switches
    icon: mdi:lightbulb-on
    entities:
      - light.kitchen_level
      - switch.dining_room_light_switch
      - light.living_room_level
      - switch.front_entry_light_switch
      - switch.garage_entry_light_switch
      # - light.lamp_left_level
      # - light.lamp_right_level
      - switch.hallway_light_switch
      - switch.basement_hallway_light_switch
      - switch.garage_light_switch
      - light.family_room_level
      - light.play_space_level
      # - light.theater_room_level
      # - light.theater_walls_level
      # - light.bedroom_master_level
      # - switch.bedroom1_light_switch
      # - switch.bedroom2_light_switch
      # - switch.bedroom3_light_switch
      # - switch.bedroom4_light_switch
      - switch.outside_front_light_switch
      - switch.outside_side_light_switch
      - switch.outside_back_light_switch

automation:
  - alias: "[Lights] Front on at Night"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:20:00"
    condition:
      - condition: time
        before: "22:30:00"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.outside_front_light_switch

  - alias: "[Lights] Front off at Night"
    trigger:
      - platform: time
        at: "22:30:00"
    action:
      - service: homeassistant.turn_off
        entity_id: switch.outside_front_light_switch

  - alias: "[Lights] Turn on when Arrive"
    trigger:
      - platform: state
        entity_id: group.people
        from: "not_home"
        to: "home"
    condition:
      - condition: sun
        after: sunset
        after_offset: "-0:30:00"
      - condition: time
        before: "23:59:59"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.garage_entry_light_switch
      - service: light.turn_on
        entity_id: light.living_room_level
        data:
          brightness: 50
      - service: notify.join_users
        data_template:
          title: Welcome Home
          message: "The lights have been turned on."
          data:
            icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lightbulb-on.png"
            smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
      - delay: "00:10:00"
      - service: homeassistant.turn_off
        entity_id: switch.garage_entry_light_switch

  - alias: "[Lights] Turn off when Away"
    trigger:
      - platform: state
        entity_id: group.people
        from: "home"
        to: "not_home"
        for:
          minutes: 10
    condition:
      - condition: sun
        after: sunrise
        after_offset: "00:45:00"
      - condition: sun
        before: sunset
        before_offset: "-00:45:00"
    action:
      - service: homeassistant.turn_off
        entity_id: group.all_light_switches
      - service: notify.join_users
        data_template:
          title: Lights Out
          message: "The lights have been turned off since no one is home."
          data:
            icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/lightbulb.png"
            smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"
