###########################################################
# Package: Media Player
###########################################################

homeassistant:
  customize_glob:
    "media_player.emby_*":
      icon: mdi:emby

  customize:
    media_player.yamaha_receiver:
      friendly_name: Yamaha Receiver
      icon: mdi:music-box

    media_player.yamaha_receiver_zone_2:
      friendly_name: Yamaha Receiver Zone 2
      icon: mdi:music-box
      hidden: true

    media_player.onkyo_receiver:
      friendly_name: Onkyo Receiver
      icon: mdi:music-box

    media_player.onkyo_receiver_zone_2:
      friendly_name: Onkyo Receiver Zone 2
      icon: mdi:music-box
      hidden: true

    media_player.onkyo_receiver_zone_3:
      friendly_name: Onkyo Receiver Zone 3
      icon: mdi:music-box
      hidden: true

recorder:
  exclude:
    entities:
      - media_player.onkyo_receiver_zone_2
      - media_player.onkyo_receiver_zone_3
      - media_player.emby__dlna__rxv679
      - media_player.emby__dlna__txnr809
      - media_player.emby__dlna__xbr65x900e
      - media_player.emby__emby_mobile__chrome
      - media_player.emby__generic__lantea

influxdb:
  exclude:
    entities:
      - media_player.onkyo_receiver_zone_2
      - media_player.onkyo_receiver_zone_3
      - media_player.emby__dlna__rxv679
      - media_player.emby__dlna__txnr809
      - media_player.emby__dlna__xbr65x900e
      - media_player.emby__emby_mobile__chrome
      - media_player.emby__generic__lantea

media_player:
  - platform: onkyo
    host: !secret media_player_onkyo_host
    sources:
      tv-cd: "TV"

  - platform: emby
    host: !secret media_player_emby_host
    api_key: !secret media_player_emby_api_key

  - platform: roku
    host: !secret media_player_roku_host

  - platform: yamaha
    host: !secret media_player_yamaha_host
    source_ignore:
      - "AUDIO1"
      - "AUDIO2"
      - "AUX"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "HDMI4"
      - "HDMI5"
      - "NET RADIO"
      - "Napster"
      - "Rhapsody"
      - "SiriusXM"
      - "Spotify"
    source_names:
      AV1: "TV"
      HDMI1: "Computer"
      HDMI2: "PS3"
      HDMI3: "XBox"
    zone_ignore:
      - "Zone_2"

automation:
  - alias: "[Media] Shield Living Room Playing at Night"
    initial_state: false
    trigger:
      - platform: state
        entity_id: media_player.emby_living_room
        from: "idle"
        to: "playing"
      - platform: state
        entity_id: media_player.emby_living_room
        from: "paused"
        to: "playing"
    condition:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: or
        conditions:
        - condition: template
          value_template: "{{ states.media_player.emby_living_room.attributes.media_content_type == 'tvshow' }}"
        - condition: template
          value_template: "{{ states.media_player.emby_living_room.attributes.media_content_type == 'movie' }}"
    action:
      - service: homeassistant.turn_on
        entity_id: light.living_room
        data:
          brightness: 20
          transition: 5

  - alias: "[Media] Shield Living Room Paused at Night"
    initial_state: false
    trigger:
      - platform: state
        entity_id: media_player.emby_living_room
        from: "playing"
        to: "paused"
    condition:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: or
        conditions:
        - condition: template
          value_template: "{{ states.media_player.emby_living_room.attributes.media_content_type == 'tvshow' }}"
        - condition: template
          value_template: "{{ states.media_player.emby_living_room.attributes.media_content_type == 'movie' }}"
    action:
      - service: homeassistant.turn_on
        entity_id: light.living_room
        data:
          brightness: 80
          transition: 10

  - alias: "[Media] Family Room Auto Off"
    initial_state: false
    trigger:
      - platform: state
        entity_id: media_player.family_room
        to: "home"
    condition:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - delay: "00:10:00"
      - service: remote.turn_off
        entity_id: remote.family_room
      - service: input_select.select_option
        entity_id: input_select.remote_family_room
        data_template:
          option: Select Activity

  - alias: "[Media] Shield Bedroom Auto Off"
    initial_state: false
    trigger:
      - platform: state
        entity_id: media_player.emby_bedroom
        from: "playing"
        to: "idle"
    condition:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - delay: "00:10:00"
      - service: remote.turn_off
        entity_id: remote.bedroom
      - service: input_select.select_option
        entity_id: input_select.remote_bedroom
        data_template:
          option: Select Activity
