###########################################################
# Package: MQTT
###########################################################

homeassistant:
  customize:
    script.notify_mqtt:
      hidden: true

mqtt:
  broker: !secret mqtt_host
  client_id: hass
  username: !secret mqtt_username
  password: !secret mqtt_password

script:
  notify_mqtt:
    sequence:
      - service: mqtt.publish
        data_template:
          # "topic/path/here"
          topic: "{{ topic }}"
          # "title|body|image"
          payload: "{{ message }}"
          retain: true
