###########################################################
# Package: Pi-hole
#   Automation is located in the automation directory
#   https://community.home-assistant.io/t/pi-hole-switch/22004
###########################################################

homeassistant:
  customize:
    script.enable_pihole:
      icon: mdi:security-network
      action_name: Enable

    input_select.pihole_time:
      icon: mdi:calendar-clock

recorder:
  exclude:
    entities:
      - input_select.pihole_time
      - script.enable_pihole

influxdb:
  exclude:
    entities:
      - input_select.pihole_time
      - script.enable_pihole

group:
  pihole:
    name: Pi-hole Status
    entities:
      - sensor.pihole_status
      - script.enable_pihole
      - input_select.pihole_time
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_cached
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_dns_queries_today
      - sensor.pihole_dns_unique_clients
      - sensor.pihole_dns_unique_domains
      - sensor.pihole_domains_blocked

sensor:
  - platform: pi_hole

  - platform: command_line
    name: Pi-hole Status
    command: !secret pihole_status
    scan_interval: 10
    value_template: "{{ value_json.status | capitalize }}"

shell_command:
  pihole_enable: !secret pihole_enable
  pihole_disable: !secret pihole_disable

script:
  enable_pihole:
    alias: Enable Pi-hole
    sequence:
      service: shell_command.pihole_enable

input_select:
  pihole_time:
    name: Disable Time (seconds)
    options:
      - Select Time
      - 10
      - 30
      - 60
      - 300
      - 600
      - 900
      - 1800
      - 3600
    initial: Select Time
