###########################################################
# Package: Pi-hole
#   https://community.home-assistant.io/t/pi-hole-switch/22004
###########################################################

homeassistant:
  customize:
    script.enable_pi_hole:
      hidden: true

    sensor.pi_hole_status:
      icon_template: >
        {% if is_state('sensor.pi_hole_status', 'Enabled') %}
          mdi:security
        {% else %}
          mdi:security-off
        {% endif %}

    input_select.pi_hole_disable_time:
      icon: mdi:calendar-clock

recorder:
  exclude:
    entities:
      - input_select.pi_hole_disable_time
      - script.enable_pi_hole

influxdb:
  exclude:
    entities:
      - input_select.pi_hole_disable_time
      - script.enable_pi_hole

sensor:
  - platform: pi_hole
    host: !secret pi_hole_host
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today
      - domains_being_blocked
      - queries_cached
      - queries_forwarded
      - unique_clients
      - unique_domains
      - clients_ever_seen

  - platform: rest
    name: Pi-hole Status
    scan_interval: 5
    resource: !secret pi_hole_status
    value_template: "{{ value_json.status | capitalize }}"

shell_command:
  pi_hole_enable: !secret pi_hole_enable
  pi_hole_disable: !secret pi_hole_disable

script:
  enable_pi_hole:
    alias: Enable Pi-Hole
    sequence:
      service: shell_command.pi_hole_enable

input_select:
  pi_hole_disable_time:
    name: Disable Time (seconds)
    options:
      - Select Time
      - 10
      - 30
      - 60
      - 300
      - 600
      - 900
      - 1800
      - 3600
    initial: Select Time

automation:
  - alias: "[Pi-hole] Disable"
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_select.pi_hole_disable_time
    action:
      service: shell_command.pi_hole_disable

  - alias: "[Pi-hole] Reset Disable Time"
    hide_entity: true
    trigger:
      - platform: state
        entity_id: script.enable_pi_hole
      - platform: state
        entity_id: sensor.pi_hole_status
        from: "Disabled"
        to: "Enabled"
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.pi_hole_disable_time
        option: Select Time
