###########################################################
# Package: Ring Doorbell
###########################################################

homeassistant:
  customize:
    camera.front_door:
      friendly_name: Ring Last Video

    binary_sensor.ring_front_door_ding:
      friendly_name: Front Door Ring

    sensor.ring_front_door_wifi_signal_strength:
      friendly_name: Ring WiFi Signal

ring:
  username: !secret ring_username
  password: !secret ring_password

logbook:
  exclude:
    entities:
        - binary_sensor.ring_front_door_ding
        - binary_sensor.ring_front_door_motion
        - sensor.ring_front_door_last_ding
        - sensor.ring_front_door_last_motion
        - sensor.ring_front_door_volume
        - sensor.ring_front_door_wifi_signal_strength

camera:
  - platform: ring
    ffmpeg_arguments: -pred 1 -q:v 2

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

sensor:
  - platform: ring
    monitored_conditions:
      # - last_activity
      - last_ding
      - last_motion
      - volume
      # - wifi_signal_category
      - wifi_signal_strength

  - platform: template
    sensors:
      ring_last_ding:
        friendly_name: Last Ring Time
        value_template: "{{ as_timestamp(states.sensor.ring_front_door_last_ding.attributes.created_at) | timestamp_custom('%m/%d/%Y %I:%M %p', True) }}"
        icon_template: mdi:bell-ring

      ring_last_motion:
        friendly_name: Last Motion Time
        value_template: "{{ as_timestamp(states.sensor.ring_front_door_last_motion.attributes.created_at) | timestamp_custom('%m/%d/%Y %I:%M %p', True) }}"
        icon_template: mdi:run-fast

group:
  door_bell:
    name: Door Bell
    icon: mdi:doorbell-video
    entities:
      - binary_sensor.ring_front_door_ding
      - binary_sensor.ring_front_door_motion
      - sensor.ring_last_ding
      - sensor.ring_last_motion
      - camera.front_door

automation:
  - alias: "[Ring] Front Door Motion"
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_motion
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ states.remote.living_room.state != "off" }}'
    action:
      - service: notify.shield_living_room
        data_template:
          title: Door Bell
          message: "There is motion at your Front Door"
          data:
            icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/run-fast.png"
            smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

  - alias: "[Ring] Front Door Ring"
    trigger:
      - platform: state
        entity_id: binary_sensor.ring_front_door_ding
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ states.remote.living_room.state != "off" }}'
    action:
      - service: notify.shield_living_room
        data_template:
          title: Door Bell
          message: "Someone pressed the doorbell"
          data:
            icon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/doorbell-video.png"
            smallicon: "https://raw.githubusercontent.com/zanix/home-assistant-config/master/www/icons/home-assistant.png"

  # - alias: "[Ring] Turn Exterior Lights to 100% when Rung after 9PM"
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.ring_front_door_ding
  #       from: "off"
  #       to: "on"
  #   condition:
  #     - condition: time
  #       after: "21:00:00"
  #     - condition: state
  #       entity_id: sun.sun
  #       state: "below_horizon"
  #   action:
  #     - service: light.turn_on
  #       entity_id: group.exterior_lights
  #       data:
  #         brightness: 254

  # - alias: "[Ring] Reset Exterior Lights to 35% after Ring at NightM"
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.ring_front_door_ding
  #       from: "on"
  #       to: "off"
  #       for:
  #         hours: 0
  #         minutes: 30
  #         seconds: 0
  #   condition:
  #     - condition: time
  #       after: "21:00:00"
  #     - condition: state
  #       entity_id: sun.sun
  #       state: "below_horizon"
  #   action:
  #     - service: light.turn_on
  #       entity_id: group.exterior_lights
  #       data:
  #         brightness: 85
  #         transition: 60

  # - alias: "[Ring] Turn Exterior Lights to 100% when Motion Detected at Night"
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.ring_front_door_motion
  #       from: "off"
  #       to: "on"
  #   condition:
  #     - condition: time
  #       after: "21:00:00"
  #     - condition: state
  #       entity_id: sun.sun
  #       state: "below_horizon"
  #   action:
  #     - service: light.turn_on
  #       entity_id: group.exterior_lights
  #       data:
  #         brightness: 254

  # - alias: "[Ring] Reset Exterior Lights to 35% after Motion Detected at Night"
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.ring_front_door_motion
  #       from: "on"
  #       to: "off"
  #       for:
  #         hours: 0
  #         minutes: 30
  #         seconds: 0
  #   condition:
  #     - condition: time
  #       after: "21:00:00"
  #     - condition: state
  #       entity_id: sun.sun
  #       state: "below_horizon"
  #   action:
  #     - service: light.turn_on
  #       entity_id: group.exterior_lights
  #       data:
  #         brightness: 85
  #         transition: 60
