###########################################################
# Package: Solar
#   Automation is located in the automation directory
#   https://community.home-assistant.io/t/solaredge-solar-panels-support/14340
#   https://community.home-assistant.io/t/solved-parsing-a-json-value-from-an-existing-entity-in-a-template-sensor/20490/17
###########################################################

recorder:
  exclude:
    entities:
      - sensor.solaredge_rest
      - sensor.solar_last_updated

influxdb:
  exclude:
    entities:
      - sensor.solaredge_rest
      - sensor.solar_last_updated

group:
  solar_production:
    name: Solar Production
    control: hidden
    icon: mdi:power-plug
    entities:
      - sensor.solar_last_updated
      - sensor.solar_current
      - sensor.solar_today
      - sensor.solar_this_month
      - sensor.solar_this_year
      - sensor.solar_lifetime

sensor:
  - platform: jsonrest
    resource: !secret jsonrest_solaredge
    method: GET
    name: "SolarEdge REST"
    scan_interval: 3600

  - platform: template
    sensors:
      solar_last_updated:
        friendly_name: "Last Updated"
        value_template: "{{ as_timestamp(states.sensor.solaredge_rest.attributes.overview.lastUpdateTime) | timestamp_custom('%m/%d/%Y %I:%M %p', True) }}"
        icon_template: "mdi:update"

      solar_current:
        friendly_name: "Current Power"
        value_template: "{{ states.sensor.solaredge_rest.attributes.overview.currentPower.power | round(1) }}"
        unit_of_measurement: "Wh"
        icon_template: "mdi:flash"

      solar_today:
        friendly_name: "Energy Today"
        value_template: "{{ (states.sensor.solaredge_rest.attributes.overview.lastDayData.energy | float / 1000) | round(2) }}"
        unit_of_measurement: "kWh"
        icon_template: "mdi:calendar-today"

      solar_this_month:
        friendly_name: "Energy this Month"
        value_template: "{{ (states.sensor.solaredge_rest.attributes.overview.lastMonthData.energy | float / 1000) | round(2) }}"
        unit_of_measurement: "kWh"
        icon_template: "mdi:calendar-blank"

      solar_this_year:
        friendly_name: "Energy this Year"
        value_template: "{{ (states.sensor.solaredge_rest.attributes.overview.lastYearData.energy | float / 1000) | round(2) }}"
        unit_of_measurement: "kWh"
        icon_template: "mdi:calendar-multiple"

      solar_lifetime:
        friendly_name: "Lifetime Energy"
        value_template: "{{ (states.sensor.solaredge_rest.attributes.overview.lifeTimeData.energy | float / 1000000) | round(2) }}"
        unit_of_measurement: "MWh"
        icon_template: "mdi:calendar-clock"
