###########################################################
# Package: Solar
#   Automation is located in the automation directory
#   https://community.home-assistant.io/t/solaredge-solar-panels-support/14340
###########################################################

# https://monitoringapi.solaredge.com/site/495534/overview.json?api_key=<api_key>
# https://monitoringapi.solaredge.com/site/495534/details.json?api_key=<api_key>
# https://monitoringapi.solaredge.com/site/495534/currentPowerFlow.json?api_key=<api_key>
# https://monitoringapi.solaredge.com/site/495534/envBenefits.json?systemUnits=Imperial&api_key=<api_key>

# https://monitoringapi.solaredge.com/equipment/495534/list.json?api_key=<api_key>
# https://monitoringapi.solaredge.com/equipment/495534/7311859A-A3/data.json?startTime=2018-06-03%2012:00:00&endTime=2018-06-09%2012:00:00&api_key=<api_key>

group:
  solar_production:
    name: Solar Production
    control: hidden
    icon: mdi:power-plug
    entities:
      - sensor.solar_last_updated
      - sensor.solar_current
      - sensor.solar_today
      - sensor.solar_this_month
      - sensor.solar_this_year
      - sensor.solar_lifetime

sensor:
  - platform: jsonrest
    resource: https://monitoringapi.solaredge.com/site/495534/overview.json?api_key=<api_key>
    method: GET
    name: "SolarEdge REST"
    scan_interval: 3600

  - platform: template
    sensors:
      solar_last_updated:
        friendly_name: "Last Updated"
        value_template: "{{ states.sensor.solaredge_rest.attributes.overview.lastUpdateTime }}"
        icon_template: "mdi:update"

      solar_current:
        friendly_name: "Current"
        value_template: "{{ states.sensor.solaredge_rest.attributes.overview.currentPower.power | round(1) }}"
        unit_of_measurement: "Wh"
        icon_template: "mdi:flash"

      solar_today:
        friendly_name: "Yesterday"
        value_template: "{{ states.sensor.solaredge_rest.attributes.overview.lastDayData.energy | float / 1000 | round(1) }}"
        unit_of_measurement: "kWh"
        icon_template: "mdi:calendar-today"

      solar_this_month:
        friendly_name: "This Month"
        value_template: "{{ states.sensor.solaredge_rest.attributes.overview.lastMonthData.energy | float / 1000 | round(1) }}"
        unit_of_measurement: "kWh"
        icon_template: "mdi:calendar-blank"

      solar_this_year:
        friendly_name: "This Year"
        value_template: "{{ states.sensor.solaredge_rest.attributes.overview.lastYearData.energy | float / 1000 | round(1) }}"
        unit_of_measurement: "kWh"
        icon_template: "mdi:calendar-multiple"

      solar_lifetime:
        friendly_name: "Lifetime"
        value_template: "{{ states.sensor.solaredge_rest.attributes.overview.lifeTimeData.energy | float / 1000000 | round(2) }}"
        unit_of_measurement: "MWh"
        icon_template: "mdi:calendar-clock"
